trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '386ed423-ad95-4924-816d-c249f0b2d97f'
  imageRepository: 'pfeflaskcopy'
  containerRegistry: 'pfeflaskdockercontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: latest

- stage: RunContainer
  displayName: Run Docker container with memory limit
  jobs:
  - job: Run
    displayName: Run container with 6GB memory limit
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Running Docker container with memory limit..."
        docker run --memory="6g" --memory-swap="6g" -p 5000:5000 -p 11434:11434 $(containerRegistry)/$(imageRepository):latest
      displayName: 'Run Docker container with memory limits'
