trigger:
- main

resources:
- repo: self
variables:
  - group: docker-credentials  # Make sure you have DOCKER_USERNAME and DOCKER_PASSWORD stored
  imageName: 'my-flask-app'
  tag: 'latest'  # or $(Build.BuildId) if you want unique versioning

stages:
- stage: BuildAndPush
  displayName: Build and Push to Docker Hub
  jobs:
  - job: Build
    displayName: Build and Push Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(DOCKER_USERNAME)/$(imageName)
        tags: |
          $(tag)

    - script: |
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
      displayName: Docker Hub Login

    - task: Docker@2
      displayName: Push Docker image to Docker Hub
      inputs:
        command: push
        repository: $(DOCKER_USERNAME)/$(imageName)
        tags: |
          $(tag)
